"""Conversation 原始消息与可重建历史过程摘要的数据契约。"""

from habitus.pre.conversation.adapters import (
    AnthropicMessagesConversationAdapter,
    ClaudeCodeConversationAdapter,
    CodexRolloutConversationAdapter,
    ConversationAdaptation,
    ConversationAdapterContext,
    ConversationAdapterRegistry,
    ConversationProtocolAdapter,
    ConversationProtocolError,
    OpenAIChatCompletionsConversationAdapter,
    OpenAIResponsesConversationAdapter,
    OpenClawConversationAdapter,
)
from habitus.pre.conversation.messages import (
    ConversationBatch,
    ConversationMessage,
    ConversationMessageRole,
    ConversationMessageSchemaError,
    ConversationSegment,
    ConversationToolResultContentMode,
    ConversationToolResultStatus,
)
from habitus.pre.conversation.summaries import (
    ConversationRangeSummary,
    ConversationRangeSummaryStage,
    ConversationSegmentSummary,
    ConversationSummaryContent,
    ConversationSummarySchemaError,
    ConversationSummarySourceKind,
    ConversationSummarySourceRef,
)

__all__ = [
    "AnthropicMessagesConversationAdapter",
    "ClaudeCodeConversationAdapter",
    "CodexRolloutConversationAdapter",
    "ConversationAdaptation",
    "ConversationAdapterContext",
    "ConversationAdapterRegistry",
    "ConversationProtocolAdapter",
    "ConversationProtocolError",
    "OpenAIChatCompletionsConversationAdapter",
    "OpenAIResponsesConversationAdapter",
    "OpenClawConversationAdapter",
    "ConversationBatch",
    "ConversationMessage",
    "ConversationMessageRole",
    "ConversationMessageSchemaError",
    "ConversationRangeSummary",
    "ConversationRangeSummaryStage",
    "ConversationSegment",
    "ConversationSegmentSummary",
    "ConversationSummaryContent",
    "ConversationSummarySchemaError",
    "ConversationSummarySourceKind",
    "ConversationSummarySourceRef",
    "ConversationToolResultContentMode",
    "ConversationToolResultStatus",
]
