"""统一模型配置、Provider 工厂和供应商无关能力契约。"""

from habitus.model_client.client import ChatClient
from habitus.model_client.config import (
    CapabilityConfig,
    ChatModelConfig,
    ChatStructuredOutputMode,
    EmbeddingInputMode,
    EmbeddingModelConfig,
    ModelCapability,
    ProviderConfig,
    RerankModelConfig,
)
from habitus.model_client.contracts import (
    ChatCallContext,
    ChatMessage,
    ChatProvider,
    ChatRequest,
    MessageRole,
    ModelAuthenticationError,
    ModelClientError,
    ModelConfigurationError,
    ModelContentSafetyError,
    ModelDependencyError,
    ModelInputTooLargeError,
    ModelPermissionError,
    ModelQuotaError,
    ModelRateLimitError,
    ModelResponse,
    ModelResponseError,
    ModelStreamEvent,
    ModelStructuredOutputError,
    ModelTransportError,
    PreparedChatRequest,
    ProviderCapabilities,
    ReasoningOptions,
    ResponseFormat,
    StreamEventKind,
    TokenUsage,
    ToolCall,
    ToolDefinition,
)
from habitus.model_client.embedding import (
    Embedder,
    EmbeddingClient,
    EmbeddingProvider,
    EmbeddingVector,
)
from habitus.model_client.factory import ProviderBuildContext, ProviderBuilder, ProviderFactory
from habitus.model_client.json_parser import JSONParseMode, ParsedJSON, parse_json_response
from habitus.model_client.rerank import RerankClient, Reranker, RerankProvider
from habitus.model_client.schema_validation import JSONSchemaValidationError, validate_json_schema
from habitus.model_client.structured import StructuredChatClient, StructuredResponse
from habitus.model_client.token_budget import (
    estimate_text_tokens,
    estimate_utf8_bytes_tokens,
)

__all__ = [
    "CapabilityConfig",
    "ChatClient",
    "ChatCallContext",
    "ChatMessage",
    "ChatModelConfig",
    "ChatStructuredOutputMode",
    "ChatProvider",
    "ChatRequest",
    "Embedder",
    "EmbeddingClient",
    "EmbeddingInputMode",
    "EmbeddingModelConfig",
    "EmbeddingProvider",
    "EmbeddingVector",
    "JSONParseMode",
    "JSONSchemaValidationError",
    "MessageRole",
    "ModelAuthenticationError",
    "ModelCapability",
    "ModelClientError",
    "ModelConfigurationError",
    "ModelContentSafetyError",
    "ModelDependencyError",
    "ModelInputTooLargeError",
    "ModelPermissionError",
    "ModelQuotaError",
    "ModelRateLimitError",
    "ModelResponse",
    "ModelResponseError",
    "ModelStreamEvent",
    "ModelStructuredOutputError",
    "ModelTransportError",
    "PreparedChatRequest",
    "ParsedJSON",
    "ProviderBuildContext",
    "ProviderBuilder",
    "ProviderCapabilities",
    "ProviderConfig",
    "ProviderFactory",
    "ReasoningOptions",
    "RerankModelConfig",
    "RerankClient",
    "Reranker",
    "RerankProvider",
    "ResponseFormat",
    "StreamEventKind",
    "StructuredChatClient",
    "StructuredResponse",
    "TokenUsage",
    "ToolCall",
    "ToolDefinition",
    "parse_json_response",
    "validate_json_schema",
    "estimate_text_tokens",
    "estimate_utf8_bytes_tokens",
]
