"""上游 Owner-scoped 语义记录入口的稳定公共边界。"""

from behavior.ingress.adapter import SemanticIngressAdapter
from behavior.ingress.evidence_ref import EvidenceKind, EvidenceReference
from behavior.ingress.identity import SemanticRecordIdentityFactory
from behavior.ingress.model import (
    BoundarySignal,
    ClockSyncStatus,
    IngressDecision,
    IngressDecisionStatus,
    OwnerScopedSemanticRecord,
    RecordIntegrity,
    SemanticActorRole,
    SemanticModality,
    SemanticRecordInput,
    SemanticRecordInputBatch,
    SemanticRecordKind,
    SemanticSubjectRole,
)
from behavior.ingress.payloads import (
    ActionEventPayload,
    ActivitySegmentPayload,
    CoverageIntervalPayload,
    CoverageStatus,
    DeviceStatePayload,
    EnvironmentChangePayload,
    FreeTextSemanticPayload,
    InteractionCounterpartyRole,
    InteractionSegmentPayload,
    PhaseHint,
    SemanticPayload,
    SensorFactPayload,
    StateAssertionPayload,
    StateTransitionPayload,
    ToolResultPayload,
    UtteranceChannel,
    UtteranceSegmentPayload,
)
from behavior.ingress.registry import SemanticIngressAdapterRegistry
from behavior.ingress.service import Clock, SemanticIngressPreparation, SemanticRecordService, SystemClock
from behavior.ingress.trust import (
    IngressAdapterCapability,
    IngressTrustClass,
    ProducerFingerprint,
)

__all__ = [
    "ActionEventPayload",
    "ActivitySegmentPayload",
    "BoundarySignal",
    "Clock",
    "ClockSyncStatus",
    "CoverageIntervalPayload",
    "CoverageStatus",
    "DeviceStatePayload",
    "EnvironmentChangePayload",
    "EvidenceKind",
    "EvidenceReference",
    "FreeTextSemanticPayload",
    "IngressAdapterCapability",
    "IngressDecision",
    "IngressDecisionStatus",
    "IngressTrustClass",
    "InteractionCounterpartyRole",
    "InteractionSegmentPayload",
    "OwnerScopedSemanticRecord",
    "PhaseHint",
    "ProducerFingerprint",
    "RecordIntegrity",
    "SemanticActorRole",
    "SemanticIngressAdapter",
    "SemanticIngressAdapterRegistry",
    "SemanticIngressPreparation",
    "SemanticModality",
    "SemanticPayload",
    "SemanticRecordIdentityFactory",
    "SemanticRecordInput",
    "SemanticRecordInputBatch",
    "SemanticRecordKind",
    "SemanticRecordService",
    "SemanticSubjectRole",
    "SensorFactPayload",
    "StateAssertionPayload",
    "StateTransitionPayload",
    "SystemClock",
    "ToolResultPayload",
    "UtteranceChannel",
    "UtteranceSegmentPayload",
]
