"""Behavior Evidence 领域边界。"""

from behavior.evidence.adapter import (
    BehaviorSemanticAdapter,
    BehaviorSemanticInput,
    BehaviorSemanticInputBatch,
)
from behavior.evidence.content import (
    BehaviorModality,
    BehaviorRecordKind,
    BehaviorRole,
    BehaviorSemanticContent,
    ClockSyncStatus,
    EvidenceIntegrity,
)
from behavior.evidence.ingress import (
    BehaviorEvidenceIngressReceipt,
    BehaviorEvidenceIngressResult,
    BehaviorEvidenceIngressService,
    IngressReceiptStatus,
)
from behavior.evidence.ledger import BehaviorEvidenceLedger
from behavior.evidence.payloads import (
    ActionEventPayload,
    ActivitySegmentPayload,
    CommunicationChannel,
    CoverageIntervalPayload,
    CoverageStatus,
    EnvironmentChangePayload,
    FeedbackPayload,
    FeedbackPolarity,
    FreeTextSemanticPayload,
    InteractionMode,
    InteractionSegmentPayload,
    PhaseHint,
    StateAssertionPayload,
    StateTransitionPayload,
    ToolCallPayload,
    ToolResultPayload,
    ToolResultStatus,
    UtteranceSegmentPayload,
)
from behavior.evidence.provenance import (
    BehaviorOriginKind,
    BehaviorSourceDescriptor,
    BehaviorSourceProvenance,
    ProducerFingerprint,
    ProducerImplementationKind,
)
from behavior.evidence.record import BehaviorEvidenceLedgerEntry, BehaviorEvidenceRecord
from behavior.evidence.refs import (
    CausalRef,
    CausalRefKind,
    CorrelationRef,
    EvidenceKind,
    EvidenceReference,
    ProjectionRef,
    SourceEventRef,
    StreamRef,
)
from behavior.evidence.registry import BehaviorSemanticAdapterRegistry
from behavior.evidence.trust import (
    BehaviorAdapterCapability,
    BehaviorSourceTrust,
    BehaviorTimeMode,
)

__all__ = [
    "ActionEventPayload",
    "ActivitySegmentPayload",
    "BehaviorAdapterCapability",
    "BehaviorEvidenceIngressReceipt",
    "BehaviorEvidenceIngressResult",
    "BehaviorEvidenceIngressService",
    "BehaviorEvidenceLedger",
    "BehaviorEvidenceLedgerEntry",
    "BehaviorEvidenceRecord",
    "BehaviorModality",
    "BehaviorOriginKind",
    "BehaviorRecordKind",
    "BehaviorRole",
    "BehaviorSemanticAdapter",
    "BehaviorSemanticAdapterRegistry",
    "BehaviorSemanticContent",
    "BehaviorSemanticInput",
    "BehaviorSemanticInputBatch",
    "BehaviorSourceDescriptor",
    "BehaviorSourceProvenance",
    "BehaviorSourceTrust",
    "BehaviorTimeMode",
    "CausalRef",
    "CausalRefKind",
    "ClockSyncStatus",
    "CommunicationChannel",
    "CorrelationRef",
    "CoverageIntervalPayload",
    "CoverageStatus",
    "EnvironmentChangePayload",
    "EvidenceIntegrity",
    "EvidenceKind",
    "EvidenceReference",
    "FeedbackPayload",
    "FeedbackPolarity",
    "FreeTextSemanticPayload",
    "IngressReceiptStatus",
    "InteractionMode",
    "InteractionSegmentPayload",
    "PhaseHint",
    "ProducerFingerprint",
    "ProducerImplementationKind",
    "ProjectionRef",
    "SourceEventRef",
    "StateAssertionPayload",
    "StateTransitionPayload",
    "StreamRef",
    "ToolCallPayload",
    "ToolResultPayload",
    "ToolResultStatus",
    "UtteranceSegmentPayload",
]
